# Generated by Django 2.1.3 on 2018-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0002_remove_girl_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='girl',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Last name'),
        ),
    ]
